Lesson4
BogdanPan/ITEA_Python_Basics pull request #4
Opened 2019-06-15 17:48 UTC by BogdanPan

2019-06-21 16:43 UTC, pep8speaks commented
Hello @BogdanPan! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`lesson4/list_functions.py`](https://github.com/BogdanPan/ITEA_Python_Basics/blob/560e4aa69fef4c17b234101bdad73945cb3efb5c/lesson4/list_functions.py):

> [Line 3:80](https://github.com/BogdanPan/ITEA_Python_Basics/blob/560e4aa69fef4c17b234101bdad73945cb3efb5c/lesson4/list_functions.py#L3): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 20:80](https://github.com/BogdanPan/ITEA_Python_Basics/blob/560e4aa69fef4c17b234101bdad73945cb3efb5c/lesson4/list_functions.py#L20): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> [Line 21:80](https://github.com/BogdanPan/ITEA_Python_Basics/blob/560e4aa69fef4c17b234101bdad73945cb3efb5c/lesson4/list_functions.py#L21): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> [Line 62:80](https://github.com/BogdanPan/ITEA_Python_Basics/blob/560e4aa69fef4c17b234101bdad73945cb3efb5c/lesson4/list_functions.py#L62): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)

* In the file [`lesson4/n_numbers_of_zeros_and_ones_in_a_row.py`](https://github.com/BogdanPan/ITEA_Python_Basics/blob/560e4aa69fef4c17b234101bdad73945cb3efb5c/lesson4/n_numbers_of_zeros_and_ones_in_a_row.py):

> [Line 18:80](https://github.com/BogdanPan/ITEA_Python_Basics/blob/560e4aa69fef4c17b234101bdad73945cb3efb5c/lesson4/n_numbers_of_zeros_and_ones_in_a_row.py#L18): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 30:80](https://github.com/BogdanPan/ITEA_Python_Basics/blob/560e4aa69fef4c17b234101bdad73945cb3efb5c/lesson4/n_numbers_of_zeros_and_ones_in_a_row.py#L30): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)

* In the file [`lesson4/recursive_bubble_sort.py`](https://github.com/BogdanPan/ITEA_Python_Basics/blob/560e4aa69fef4c17b234101bdad73945cb3efb5c/lesson4/recursive_bubble_sort.py):

> [Line 11:80](https://github.com/BogdanPan/ITEA_Python_Basics/blob/560e4aa69fef4c17b234101bdad73945cb3efb5c/lesson4/recursive_bubble_sort.py#L11): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (118 > 79 characters)

* In the file [`lesson4/string_functions.py`](https://github.com/BogdanPan/ITEA_Python_Basics/blob/560e4aa69fef4c17b234101bdad73945cb3efb5c/lesson4/string_functions.py):

> [Line 61:80](https://github.com/BogdanPan/ITEA_Python_Basics/blob/560e4aa69fef4c17b234101bdad73945cb3efb5c/lesson4/string_functions.py#L61): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

2019-06-22 10:41 UTC, itea-artem requested changes

2019-06-22 10:41 UTC, itea-artem commented on lesson4/list_functions.py
> +        inp_list[len(inp_list)-1] = inp_str  # insert at last index of list
append

2019-06-22 10:41 UTC, itea-artem commented on lesson4/list_functions.py
> +def insert(inp_list, inp_index, inp_str):
Very uneffective algorithm. Just use second list

2019-06-22 10:41 UTC, itea-artem commented on lesson4/list_functions.py
> +        if i == inp_str and first_run:  # removing
you should avoid first_run variables

2019-06-22 10:41 UTC, itea-artem commented on lesson4/list_functions.py
> +            continue
!

2019-06-22 11:16 UTC, BogdanPan commented on lesson4/list_functions.py
> +        inp_list[len(inp_list)-1] = inp_str  # insert at last index of list
Changed.

2019-06-22 11:16 UTC, BogdanPan commented on lesson4/list_functions.py
> +def insert(inp_list, inp_index, inp_str):
Done

2019-06-22 11:16 UTC, BogdanPan commented on lesson4/list_functions.py
> +        if i == inp_str and first_run:  # removing
Done

2019-06-22 11:16 UTC, BogdanPan commented on lesson4/list_functions.py
> +            continue
Done

2019-07-21 12:08 UTC, itea-artem approved these changes
6/8

2019-07-21 12:08 UTC, itea-artem commented on lesson4/string_functions.py
> +def replace(inp_data, what_to_replace, replace_with):
https://github.com/Vilya22/ITEA_Python_Basics/blob/lesson4/lesson4/homework3.py#L19
На будущее разбивайте слишком длинные функции на вспомогательные.

2019-07-21 13:00 UTC, merged